### ISSUE TITLE
unit change for eu & application file on github

### ISSUE THREAD

**Issue by pejotigrek** [pauleeeeee/2019-nCoV-pebble-tracker#1]
hi!

first of all - great job! I've found your .pbw on r/pebble, and played with that a little. unfortunately I am no programmer by any means, so all I can do is suggest something, pretty please something & patiently wait if it's going to be implemented ;)

I've got two things only, which seems easy to me, but who knows.. ;)

first:
can you make the .pbw file available also here, on github, as a [release](https://github.com/pauleeeeee/2019-nCoV-pebble-tracker/releases)? that would be so much easier to keep track of the app :)

second thing:
I'm EU based, therefore I use metric system, but app shows me the miles still. although I know the conversion rate so can do a quick math, it would be totally cool if one could choose the unit in settings.

oh, and the question out of curiosity - do you know on what does it depend that different file managers can or cannot open your app with Pebble App to install it? like - system file browser [Pixel 2XL, Android 10] doesn't recognize it as Pebble Application, [X-plore File Manager](https://play.google.com/store/apps/details?id=com.lonelycatgames.Xplore) (that I use daily as main driver) doesn't recognize it also, but Total Commander did with no problems. is it something system/file browser based problem or some headers maybe are missing in .pbw app? [I'm not an expert, just thinking out loudly].

**Comment by pauleeeeee** [comment]
Hey thanks for the ideas! Didn't even think about putting the pbw here as a release. I will add unit option to settings page this morning on the train. 

Not sure about the sideloading differences. I am no expert either. Maybe something missing the package.json file? Will look into it

**Comment by pauleeeeee** [comment]
Okay I added a release but am going to wait to close this issue till I update the repository with the code. I am pretty new to using github so gotta figure that out. But, you should be able to sideload that new version and configure custom units. Hopefully there won't be any issues with updating like this.

**Comment by pejotigrek** [comment]
great! tested it and both - release link & units settings work fine :)

only one thing I could add is to change kilometers shortcut from "ki" to "km" [this is the proper form].

thanks!

**Comment by pauleeeeee** [comment]
Don't know why I forgot that... must be that silly ol' American brain :)

I updated the pbw in place in the release (did not make a new release for the fix).
